## Data Prep for Project 1
Data was retrieved from Amazon AWS via Athena
<br>
Raw dataset was too large (2GB) to store on GitHub
<br>
Broke it down into a small enough chunk by focusing on Lego only
<br>
<br>
DO NOT RUN THIS LOCALLY - FILE LOCATIONS ARE NOT IN THE REPO
<br>
This is intended only to show some of the up front data prep

In [1]:
import pandas as pd
import numpy as np

#Using a 2GB datafile pulled down via Amazon AWS - Athena
#Search criteria was review data, all columns
#and filtered where product_name = 'toys'
file = 'C:/Users/ahumb/Downloads/2570d538-b194-42d0-80b6-511d4e3a8fc4.csv'

#setting the csv reader
df = pd.read_csv(file)
#df.head()

In [2]:
#Running a quick count
df.count()

marketplace          4981601
customer_id          4981601
review_id            4981601
product_id           4981601
product_parent       4981601
product_title        4981555
star_rating          4981601
helpful_votes        4981601
total_votes          4981601
vine                 4981601
verified_purchase    4981601
review_headline      4981569
review_body          4981224
review_date          4981601
year                 4981601
product_category     4981601
dtype: int64

In [3]:
#Dropping the empties
df=df.dropna(how='any')

In [4]:
#Running another count to confirm we're good to go
df.count()

marketplace          4981146
customer_id          4981146
review_id            4981146
product_id           4981146
product_parent       4981146
product_title        4981146
star_rating          4981146
helpful_votes        4981146
total_votes          4981146
vine                 4981146
verified_purchase    4981146
review_headline      4981146
review_body          4981146
review_date          4981146
year                 4981146
product_category     4981146
dtype: int64

In [5]:
#Showing the columns and their data types
df.dtypes

marketplace          object
customer_id           int64
review_id            object
product_id           object
product_parent        int64
product_title        object
star_rating           int64
helpful_votes         int64
total_votes           int64
vine                 object
verified_purchase    object
review_headline      object
review_body          object
review_date           int64
year                  int64
product_category     object
dtype: object

In [6]:
#Taking a look at the first 5 rows
df.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,year,product_category
0,US,23787544,R1FDBNIYAON9FO,B001CT83XY,539553731,Dowling Magnets Alnico Science Kit,5,0,0,N,Y,Kids gift,The child who received this for a gift is begi...,16086,2014,Toys
1,US,24463985,RDBITPARVSUU0,B00FE0Q3CA,680997900,Venom 25C 1S 120mAh 3.7 LiPO Battery for Eflig...,4,1,1,N,Y,good product,"good product, doesn't last a very long time, b...",16452,2015,Toys
2,US,42721806,R7BHLBJQ2RIJM,B00CS0F0NC,853492030,Nerf N-Strike Elite Battle App Tactical Rail M...,4,0,1,N,Y,Cool new way to use Nerf guns.,We bought these for our kids for Christmas and...,16086,2014,Toys
3,US,4063478,R1J9XYZWKTP8HM,B00ITOB7OC,52702733,"Nickelodeon, Paw Patrol Racers - Rocky",5,0,0,N,Y,the price was right for this toy,My son loves these toys. The price was reasona...,16452,2015,Toys
4,US,19700693,ROLRQGFE3K2D9,B00BSWS3L2,619656194,Despicable Me 2 Dave Deluxe Action Figure with...,5,0,0,N,Y,Loved it!,It was exactly what I had been searching for. ...,16086,2014,Toys

In [8]:
#Due to file size (2GB) and GitHub file size limits (of 25MB)
#We decided to pull just LEGO data and perform some international comparisons

#Setting a new dataframe where the product title contains 'LEGO'
#Also resetting the index since we're in a new dataframe
lego_df = pd.DataFrame(df[df['product_title'].str.match('LEGO')])
lego_df = lego_df.reset_index()
del lego_df['index']

In [9]:
#When leaving in the body of the reviews, the output file ends up being around 52MB
#By removing reviews and product_type the output file ends up being 22MB

#sets new dataframe and previews the first 5 rows
lego_no_review_df = lego_df.filter(['marketplace','customer_id','review_id','product_id','product_parent','product_title',
                         'star_rating','helpful_votes','total_votes','vine','verified_purchase','review_headline',
                         'review_date','year'],axis=1)
lego_no_review_df.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_date,year
0,US,52187079,R22E1FW4RGFOC5,B00EXJM3P4,923528669,LEGO The Hobbit Dol Guldur Battle 79014,5,0,0,N,Y,LOTR + Lego = nirvana....,16452,2015
1,US,38801121,RSKHR5CR97VFJ,B0094J117O,38301932,LEGO® CITY® Museum Break-in & Police Unit w/ S...,5,0,0,N,Y,FUN,16086,2014
2,US,17257015,R12HDWC8E4AM74,B00BG5FYY0,702261848,LEGO Hero Factory 44012 EVO Action Figure Playset,4,1,2,N,Y,ok,16086,2014
3,US,14537742,R1JH6KW5DMZW5O,B00A852QIG,377101347,LEGO DUPLO My First Construction Site 10518,5,0,0,N,Y,Five Stars,16452,2015
4,US,14508692,R2I2XNCOQVZHYS,B00A8O87DA,912541874,LEGO LEGO Hero Factory BREEZ 44006,5,0,0,N,Y,Wonderful,16086,2014

In [18]:
#This outputs the file locally to Andy's computer
#File will be uploaded to GitHub manually
lego_no_review_df.to_csv('C:/Users/ahumb/Downloads/lego_no_review_df.csv', header=True,sep=',')
lego_no_review_df.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_date,year
0,US,52187079,R22E1FW4RGFOC5,B00EXJM3P4,923528669,LEGO The Hobbit Dol Guldur Battle 79014,5,0,0,N,Y,LOTR + Lego = nirvana....,16452,2015
1,US,38801121,RSKHR5CR97VFJ,B0094J117O,38301932,LEGO® CITY® Museum Break-in & Police Unit w/ S...,5,0,0,N,Y,FUN,16086,2014
2,US,17257015,R12HDWC8E4AM74,B00BG5FYY0,702261848,LEGO Hero Factory 44012 EVO Action Figure Playset,4,1,2,N,Y,ok,16086,2014
3,US,14537742,R1JH6KW5DMZW5O,B00A852QIG,377101347,LEGO DUPLO My First Construction Site 10518,5,0,0,N,Y,Five Stars,16452,2015
4,US,14508692,R2I2XNCOQVZHYS,B00A8O87DA,912541874,LEGO LEGO Hero Factory BREEZ 44006,5,0,0,N,Y,Wonderful,16086,2014

In [15]:
#We wanted to store the review work somewhere and created a data frame specific for reviews
#Since review_id is unique we decided to keep it so that we could potentially merge it back for analysis
lego_review_only_df = lego_df.filter(['review_id','review_body'],axis=1)
lego_review_only_df.head()

        review_id                                        review_body
0  R22E1FW4RGFOC5  Purchased for an adult Lego fiend...he also ha...
1   RSKHR5CR97VFJ  LEGO is always superb! Never fails to live up ...
2  R12HDWC8E4AM74  I thought the bigger the game ..<br /><br />th...
3  R1JH6KW5DMZW5O                               My grandson love it!
4  R2I2XNCOQVZHYS  This was a gift for a family  member and I was...

In [19]:
#This outputs the reviews locally to Andy's computer
#Unfortunately file size is an issue again at around 33MB
lego_review_only_df.to_csv('C:/Users/ahumb/Downloads/lego_review_only_df.csv', header=True,sep=',')
lego_review_only_df.head()

        review_id                                        review_body
0  R22E1FW4RGFOC5  Purchased for an adult Lego fiend...he also ha...
1   RSKHR5CR97VFJ  LEGO is always superb! Never fails to live up ...
2  R12HDWC8E4AM74  I thought the bigger the game ..<br /><br />th...
3  R1JH6KW5DMZW5O                               My grandson love it!
4  R2I2XNCOQVZHYS  This was a gift for a family  member and I was...